name: Roll 'em

on:
  issues:
    types:
    - opened
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  roll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.
      with:
        chance: 100
